import { GoogleGenAI } from '@google/genai';

export const runtime = 'nodejs';

export async function POST(req) {
  try {
    const { prompt } = await req.json();
    
    if (!prompt) {
      return new Response(JSON.stringify({ error: "Prompt is required" }), { status: 400 });
    }

    // Initialize without key if Vertex is used, but for simplicity, we use API key via Google AI Studio
    // If you are using Vertex AI, you can initialize the client correspondingly.
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
    
    // We will use standard generateContent to ask a small model to generate the image, or directly use imagen if available.
    // Wait, the SDK has an image generation endpoint if we use imagen. If not, we can mock it or use an external URL.
    // Assuming Imagen endpoint through Vertex/Gemini Developer API:
    let base64Image;
    
    try {
        const response = await ai.models.generateImages({
            model: 'imagen-3.0-generate-002',
            prompt: prompt + ' -- high quality, cinematic lighting, digital art masterpiece',
            config: {
                numberOfImages: 1,
                aspectRatio: '16:9',
                outputMimeType: 'image/jpeg'
            }
        });
        
        if (response.generatedImages && response.generatedImages.length > 0) {
            // SDK returns `image.imageBytes` as string usually
            base64Image = response.generatedImages[0].image.imageBytes;
        } else {
            throw new Error("No image generated by the API.");
        }
    } catch(imagenError) {
        console.error("Imagen failed, providing a fallback mock image:", imagenError);
        // Provide a fallback placeholder if they don't have access to Imagen 3 yet.
        return new Response(JSON.stringify({ 
            imageUrl: `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=800&height=450&nologo=true`
        }), { status: 200, headers: { 'Content-Type': 'application/json' } });
    }

    return new Response(JSON.stringify({ 
        imageUrl: `data:image/jpeg;base64,${base64Image}`
    }), { status: 200, headers: { 'Content-Type': 'application/json' } });

  } catch (error) {
    console.error("Error generating image:", error);
    return new Response(JSON.stringify({ error: error.message }), { status: 500 });
  }
}
